# Snipe-IT tasks - main.yml
---
- name: create snipe-it user
  user:
    name: snipe-it
    comment: "Snipe-IT User"
    group: www-data
    shell: /bin/bash
    system: yes

- name: install required packages - snipe-it
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - curl
    - php7.0-bcmath
    - php7.0-cli
    - php7.0-curl
    - php7.0-fpm
    - php7.0-ldap
    - php7.0-mysql
    - php7.0-mcrypt
    - php7.0-gd
    - php7.0-xml
    - php7.0-mbstring
    - php7.0-zip
    - patch
    - unzip

- name: install composer
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  args:
    creates: /usr/local/bin/composer

- name: include mysql tasks
  include_tasks: mysql.yml

- name: create snipe-it directory
  file:
    path: /srv/snipe-it
    state: directory
    owner: snipe-it
    group: www-data
    mode: 0750

- name: clone snipe-it github repo
  git:
    repo: 'https://github.com/snipe/snipe-it'
    dest: /srv/snipe-it
    clone: yes
    update: yes
    force: yes
    version: "{{ snipeit_version }}"
  become_user: snipe-it
  notify:
    - restart nginx
    - restart php7
  register: clone_snipeit_repo

- name: configure snipe-it git repo
  git_config:
    name: core.fileMode
    repo: /srv/snipe-it
    scope: local
    value: false
  become_user: snipe-it

- name: set ownership and persmisons of snipe-it sub-directories
  file:
    path: "/srv/snipe-it/{{ item }}"
    state: directory
    mode: 0770
    recurse: yes
  with_items:
    - bootstrap
    - public
    - storage

- name: run php upgrade
  command: php /srv/snipe-it/upgrade.php
  become_user: snipe-it
  when: clone_snipeit_repo is changed

- name: install dependencies with composer
  composer:
    command: install
    working_dir: /srv/snipe-it
    no_dev: yes
    prefer_source: yes
  become_user: snipe-it

- name: apply snipe-it .env template
  template:
    src: env.j2
    dest: /srv/snipe-it/.env
    owner: snipe-it
    group: www-data
    mode: 0640
  notify:
    - restart nginx
    - restart php7

- name: include nginx tasks
  include_tasks: nginx.yml

- name: ensure web services are running
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - nginx
    - php7.0-fpm
